- README.md
According to https://github.com/stackblitz/webcontainer-core/issues/1067, the embed view which was used is not supported by all browsers.
My change is removing the embed parameter to open the project in Stackblitz normal mode :)
> docs: update stackblitz url

- src/client/components/DocDetails.vue
- src/client/logic/documentations.ts
- src/client/pages/documentations.vue
- src/types.ts
If I hadn’t looked at the source code, I wouldn’t know what caused the vue document in the document tab to fail to open, so for a better experience, I added a reminder and set that the website that cannot be opened in the form of an iframe will be in the form of a tab Open
> feat: add tips for unable to embed website

- src/client/composables/state.ts
- src/client/pages/settings.vue
- src/node/Container.vue
On some large-sized screens, it is inconvenient to click the `vue logo` to close the modal each time the webpage is full-screen. In fact, you only want the modal to be there when you are viewing the routing track. Provide a configuration item to decide whether you want to click to close
> feat: support click outside to close modal

- src/node/views/Main.vue
> fix: use `div` tag instead of `button` to compatible with uni-app

- .vscode/settings.json
- src/client/logic/components/tree.ts
closes #86 
from https://github.com/vuejs/devtools/blob/122207de2ed79d839c572438b095ce3f5ea1fed9/packages/app-backend-vue3/src/components/tree.ts#L178-L186
Need an `unique id` to check if it is collected. Currently uses `uid`
> fix(components): keep-alive components repeated collection

- src/client/pages/graph.vue
- src/client/styles/main.css
There may be many similar file names in the project, this feature makes easy to see more complete file path
> feat(graph): show full path while hovering node

- src/client/components/Notification.vue
- src/client/components/StateFields.vue
- src/client/composables/context.ts
- src/client/composables/editor.ts
- src/client/pages/components.vue
- src/client/uno.config.ts
`JSON.stringify` will report an error when converting objects with internal circular references. At this time, the correct prompt message should appear.
> fix(components): show error message when copy failed

- src/client/pages/__eyedropper.vue
> feat(eyedropper): support copy and rgb color model

- src/node/views/Main.vue
Maybe we should hide the devtool while print.
> feat: hide devtools panel during print media

- packages/client/components/AssetListItem.vue
- packages/client/pages/assets.vue
Sync from https://github.com/nuxt/devtools/pull/335
Closes #154
> feat(assets): tree view for list mode

- packages/client/styles/main.css
由于Firefox不支持 `-webkit-scrollbar` 属性，所以在 .no-scrollbar 中使用 `scrollbar-width` 属性解决滚动条。
修改前：
修改后：
> fix(client): hide scrollbar in Firefox

- packages/client/pages/__eyedropper.vue
``` javascript
open().then((res) => {
hexColor.value = res.sRGBHex
}).catch(() => {
close()
})
```
在调用open时候，遇到不支持的浏览器时，open方法会返回`undefined`，导致上面的`res.sRGBHex`报错，并被catch语句捕获，运行close方法，这样就无法显示feedback信息。解决方法是，让open返回一个空对象，这样在then中就不会发生错误。
> fix(eyedropper): show feedback in error boundary

- packages/client/components/AssetDetails.vue
- packages/client/components/AssetPreview.vue
Synchronizing changes from https://github.com/nuxt/devtools/pull/347
Support preview video assets in devtools.
> feat: video assets preview

- packages/client/components/AssetDetails.vue
- packages/client/components/DrawerRight.vue
- packages/client/components/Notification.vue
- packages/client/composables/context.ts
- packages/client/logic/rpc.ts
- packages/client/pages/assets.vue
- packages/node/client.d.ts
- packages/node/src/features/assets.ts
- packages/node/src/vite.ts
- packages/ui-kit/src/components/Dialog.vue
#
Closes: #174 
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/3993028/44894505-79cc-45ce-80f1-b358c153ee08
> feat(assets): add rename and delete action

- packages/client/components/RoutesTable.vue
- packages/client/logic/routes.ts
- packages/playground/src/main.ts
- packages/ui-kit/src/components/Dropdown.vue
closes #193 
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/49969959/49b7b977-f086-4e49-8bee-3f6670dc1aa2
> feat: dynamic show route meta fields

- packages/client/pages/components.vue
close https://github.com/webfansplz/vite-plugin-vue-devtools/issues/208
> fix: obscured content on components page when scrolling

- packages/client/components/Notification.vue
Fixes this case:
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/49969959/33a656cd-3426-4b6d-b61c-dd76263055d7
> fix: increment `z-index` of `Notification` component

- packages/client/components/IframeView.vue
Fix the following case:
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/3993028/0e16dcd5-ae43-4a13-9823-7f90a356049e
> fix: set correct loading state in  iframeView

- packages/node/src/views/ComponentInspector.vue
- packages/node/src/views/Main.vue
> fix: hide component inspector overlay when bounds is incomplete

- packages/core/src/compiler/trace-rerender.ts
- packages/playground/package.json
- packages/playground/src/App.vue
- packages/playground/src/components/TSX.vue
- packages/playground/vite.config.ts
- pnpm-lock.yaml
closes #264 
This issue will occur when using `sfc + tsx`.
If the lang of an sfc is `tsx/jsx`, it will transform this file twice, (once `vite-plugin-vue`, once `vite-plugin-vue-jsx`)
We need to prevent duplicate injections.
> fix(core): fix analyzer duplicate injection code
