src/client/auto-imports.d.ts, src/client/pages/overview.vue, src/client/utils/index.ts, src/node/Container.vue, tsconfig.json
this PR, supports the window resize
=> feat: make devtools panel resizeable

src/client/App.vue, src/client/logic/timeline.ts
=> perf: close perf timeline to avoid performance issue

src/node/Container.vue
Fix component-inspector page size
=> fix: fix component-inspector size

src/node/rpc/assets.ts
=> feat: full assets support

src/client/logic/routes.ts
=> feat: dynamic route support

src/client/logic/pinia.ts
=> fix: pinia internal variable access warning

src/client/pages/npm.vue
=> chore(npm): remove runtime console

README.md, src/node/index.ts
=> feat: introducting `appendTo` option

src/client/components/IframeView.vue
=> feat: iframe view loading

src/client/pages/npm.vue, src/node/index.ts, src/node/rpc/npm.ts, src/node/rpc/packages.ts, src/types.ts
=> feat(npm): show project dependencies 

src/client/App.vue, src/client/composables/tabs.ts, src/client/pages/__eyedropper.vue, src/client/uno.config.ts, src/node/Container.vue, src/types.ts
=> feat: eyedropper

src/node/views/utils.ts
see: https://github.com/vueuse/vueuse/blob/main/packages/core/useStorage/index.ts#L56
and: https://github.com/vueuse/vueuse/blob/main/packages/core/useStorage/index.ts#L192-L194
fix storage listener bug
=> fix: storage listener with vueuse bug

src/client/components/StateFieldsTree.vue
Closes https://github.com/webfansplz/vite-plugin-vue-devtools/issues/43
support select dblclick copy key, I'm not sure if it's reasonable to do so.
=> feat(components): add dblclick event to copy state key

src/node/rpc/assets.ts
The JPEG XL image format has been added.
=> feat(assets): add image file type `jxl` format to check

src/client/store/tab.ts
=> fix: ungrouped has not been initialized when remove group

package.json
=> feat!: support object hooks, require Vite 3.1

.github/renovate.json
=> fix(renovate): remove unknown rules

playground/src/App.vue
=> chore(playground): add space between btns

playground/src/pages/About.vue
=> chore(playground): enhance `about` page

src/client/logic/app.ts
remove unnecessary object copying operations.
=> chore: remove unnecessary code

src/client/components/Notification.vue
=> feat(components): keep notification visible when hovering

src/client/components/Notification.vue
=> chore(components): fix lint

playground/src/components/HelloWorld.vue, src/client/logic/global.ts, src/client/logic/graph.ts, src/client/logic/rpc.ts, src/client/pages/components.vue, src/client/pages/graph.vue, src/client/pages/inspect.vue
=> feat(components): show fullPath when hovering open-in-editor button

src/client/pages/__eyedropper.vue
=> fix(eyedropper): close when cancel eyeDropper by `ESC`

package.json, packages/client/logic/graph.ts, packages/client/pages/graph.vue
Debounce watch `glob` and `searchText` for a better performance.
Improve `graph` page performance is not finished yet, this PR is a slight step improvement and will keep going further.
=> perf: improve graph page performance

packages/client/components/AssetGridItem.vue, packages/client/components/AssetListItem.vue, packages/client/styles/main.css
=> revert(assets): scroll-driven-animations

packages/client/pages/pinia.vue, packages/client/types.ts
=> chore: fix types

README.md, packages/node/README.md, packages/node/package.json, packages/node/src/vite.ts, pnpm-lock.yaml
=> feat: introducing `openInEditorHost` option

packages/client/pages/npm.vue, packages/client/pages/rerender-trace.vue
=> chore: improve style

packages/client/logic/components/filter.ts, packages/client/pages/components.vue
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/49969959/4348e738-1c83-4cfd-899d-5dafcb012d82
=> feat: support filter components in component tree

packages/client/composables/state.ts, packages/client/pages/settings.vue, packages/node/src/views/Main.vue, packages/node/src/views/composables.ts
Sync from https://github.com/nuxt/devtools/pull/361
Closes #185
=> feat: minimize panel on inactive

packages/client/components/AssetDetails.vue, packages/client/components/AssetPreview.vue
=> feat(assets): support audio assets preview

packages/client/components/DockingPanel.vue, packages/client/components/FullscreenButton.vue, packages/client/types.ts, packages/node/client.d.ts, packages/node/src/views/FrameBox.vue, packages/node/src/views/Main.vue
Support `fullscreen` mode to get a better UX.
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/49969959/5a16bbd1-eea4-424a-9507-1fe727f08d74
=> feat: fullscreen view mode

packages/client/components/SideNav.vue, packages/client/store/tab.ts
close https://github.com/webfansplz/vite-plugin-vue-devtools/issues/190
=> fix: sidenav group divider line

packages/client/pages/npm.vue
close https://github.com/webfansplz/vite-plugin-vue-devtools/issues/195
=> chore: npm version dropdown scroll style

packages/client/pages/settings.vue
close https://github.com/webfansplz/vite-plugin-vue-devtools/issues/204
=> chore: setting page scroll style

package.json
vite [5.0.0-beta.0](https://github.com/vitejs/vite/blob/v5.0.0-beta.0/packages/vite/CHANGELOG.md) has been released.
=> feat: compatible with `vite` 5.0

packages/client/pages/components.vue
=> fix(components): keep components tree selected state

packages/client/pages/pinia.vue
Closes https://github.com/webfansplz/vite-plugin-vue-devtools/issues/212
=> fix: add overflow auto in pinia page

packages/core/src/compiler/index.ts
fixes #227 
fixes #226 
@webfansplz , should merge it ASAP.
=> fix: incorrect sourcemap of transformed code

packages/client/App.vue, packages/client/components/DockingPanel.vue, packages/client/components/SideNav.vue, packages/client/components/SideNavItem.vue, packages/client/composables/settings.ts, packages/client/pages/settings.vue, packages/node/README.md
https://github.com/webfansplz/vite-plugin-vue-devtools/assets/43719490/88e5c0a3-c86c-4c2a-acdf-1f4eb50ac5ba
=> feat: collapsible sidebar

README.md
So far we are refactoring this codebase, which means we have no much energy to provide active support and fast response, we might need to add an announcement to notify users.
=> docs: add refactoring notice announcement

packages/client/components/Notification.vue, packages/client/components/PopupButton.vue, packages/client/composables/context.ts, packages/node/src/views/composables.ts
cloese #248 
seems like since Chome v118, the `documentPictureInPicture.requestWindow` force requires `https` protocol though in a secure context.
not sure if it is a bug or a feature.
add a fallback notification here.
=> feat(popup): fallback notification

packages/node/src/vite.ts
=> feat: respect vite base path option
